spring:
  profiles:
    active: dev

cors:
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "Content-Type,Authorization"
  allow-credentials: true